# Generated by Django 4.1.7 on 2023-06-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0025_assist_helpful_helpfulupvote'),
        ('accounts', '0005_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='upvote_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='upvoted_assists',
            field=models.ManyToManyField(related_name='upvoted_by', to='randomizer.assist'),
        ),
    ]
