# Generated by Django 4.1.7 on 2023-06-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_grid_data_alter_grid_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grid',
        ),
    ]
