# Generated by Django 4.2.2 on 2023-08-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0033_grid'),
        ('accounts', '0011_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='upvoted_assists',
            field=models.ManyToManyField(blank=True, related_name='upvoted_by', to='randomizer.assist'),
        ),
    ]
