# Generated by Django 4.1.7 on 2023-06-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0019_alter_decision_image_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='decision',
            name='tags',
            field=models.ManyToManyField(to='randomizer.tag'),
        ),
    ]
