# Generated by Django 4.1.7 on 2023-06-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0020_tag_decision_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='overview',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='tags',
            field=models.ManyToManyField(blank=True, to='randomizer.tag'),
        ),
    ]
