# Generated by Django 4.1.7 on 2023-06-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0021_decision_overview_alter_decision_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='preference',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='overview',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='situation',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
