# Generated by Django 4.1.7 on 2023-06-07 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('randomizer', '0022_decision_preference_alter_decision_overview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=255, null=True)),
                ('pros', models.TextField(blank=True, max_length=255, null=True)),
                ('cons', models.TextField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('assisted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomizer.decision')),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='randomizer.option')),
            ],
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
