# Generated by Django 4.1.7 on 2023-06-07 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0023_assist_delete_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assist',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='randomizer.option'),
        ),
    ]
