# Generated by Django 4.1.7 on 2023-06-11 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('randomizer', '0024_alter_assist_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='assist',
            name='helpful',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='HelpfulUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomizer.assist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
