# Generated by Django 4.1.7 on 2023-06-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0025_assist_helpful_helpfulupvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='assist',
            name='caution',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
