# Generated by Django 4.1.7 on 2023-06-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0026_assist_caution'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='contributor_message',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
