# Generated by Django 4.1.7 on 2023-06-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0028_userdecisioninteraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdecisioninteraction',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='userdecisioninteraction',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='userdecisioninteraction',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='userdecisioninteraction',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdecisioninteraction',
            name='last_interaction_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userdecisioninteraction',
            name='view_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
